name: Backend CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Display version
        run: python -c "import sys; print(sys.version)"
      - name: Install pipenv
        run: sudo pip install pipenv && sudo pip install flake8
      - name: Install dependencies
        run: pipenv install
      - name: Running linter
        run: pipenv run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install pipenv
        run: sudo pip install pipenv && sudo pip install flake8

      - name: Install
        run: pipenv install

      - name: Run
        run: pipenv run test

  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ${{ vars.ECR_REPOSITORY }} .
